### ISSUE TITLE
Check wasm support and enable `no-std`

### ISSUE THREAD

**Issue by jonathanpwang** [axiom-crypto/halo2-lib#1]
Currently circuit are not written with `no-std` support in mind. Testing needs to be done to see what needs to be fixed to support it. Hopefully changes needed are minimal.

**Comment by mattsse** [comment]
this actually compiles succesffully already if the jemallocator feature is disabled.

**Comment by jonathanpwang** [comment]
Oh that's great to know! I'm assuming you are referring to tests in halo2-base? 
I was afraid some tests in halo2-ecc might not work because we use environmental variables and file IO to read in some configuration files. But if everything else works then it'll be easy for downstream users to get around that. 

If you have some additions that enable wasm + an example of how to use it, we'd appreciate a PR :) 
What would be really cool is to be able to run our ECDSA in a browser for others to use.
