### ISSUE TITLE
Fix BLS signature tests in develop-ce

### ISSUE THREAD

**Issue by jonathanpwang** [axiom-crypto/halo2-lib#155]
https://github.com/axiom-crypto/halo2-lib/blob/develop-ce/halo2-ecc/src/bn254/tests/bls_signature.rs

Tests need to be reformatted after v0.4.0 breaking changes. Should be able to copy format of `tests/pairing.rs` and use the new test suite. 

@flyingnobita is a natural person to do this, but also a good few issue for anyone else who want to take it up.

**Comment by flyingnobita** [comment]
Sorry I was at a hackathon yesterday and couldn't respond sooner. Thanks for the fix!
