### ISSUE TITLE
Dynamic lookup table does not contain fixed/selector columns

### ISSUE THREAD

**Issue by kcharbo3** [axiom-crypto/halo2-lib#205]
The dynamic lookup table functionality provided in `/halo2-base/src/virtual_region/lookups/basic.rs` - https://github.com/axiom-crypto/halo2-lib/blob/267123f6ec0cc8fdaeac4312e6426f52cc810f3d/halo2-base/src/virtual_region/lookups/basic.rs#L39-L63

does not include any fixed/selector columns for the table columns. So all table columns are advice columns. This can easily lead to bugs when all rows of these advice columns are not constrained. The unconstrained rows can have any input value by the attacker, allowing them to include a false lookup.

This bug was originally seen in the Scroll/PSE zkevm circuits -  https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/866

Adding a fixed/selector column to the lookup table allows lookups to succeed only for rows where the selector is `1`. This selector should be enabled only on rows where the lookup table's advice values are set.

**Comment by jonathanpwang** [comment]
Resolved in https://github.com/axiom-crypto/halo2-lib/pull/206
