### ISSUE TITLE
backlog: cargo check fails for latest nightly toolchain

### ISSUE THREAD

**Issue by lispc** [axiom-crypto/halo2-lib#22]
i change the toolchain to nightly-2023-04-24, and run cargo check, it reports error like

```
error[E0599]: no associated item named `NUM_BITS` found for associated type `<FpChip as FieldChip<F>>::FieldType` in the current scope
   --> halo2-ecc/src/fields/fp12.rs:108:58
    |
108 |     const PRIME_FIELD_NUM_BITS: u32 = FpChip::FieldType::NUM_BITS;
    |                                                          ^^^^^^^^ associated item not found in `<FpChip as FieldChip<F>>::FieldType`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   + use ff::PrimeField;
    |

```

branch i use: release-0.3.0
(it works well for the default nightly-2022-10-28, so i just mark this as a backlog)

due to this commit: https://github.com/rust-lang/rust/commit/8996ea93b6e554148c4286e62b613f12a3ee505c

**Comment by jonathanpwang** [comment]
thanks, on our radar

**Comment by lispc** [comment]
can be solved liken this https://github.com/scroll-tech/halo2-lib/pull/10

**Comment by jonathanpwang** [comment]
Resolved in https://github.com/axiom-crypto/halo2-lib/pull/154

**Comment by Silur** [comment]
I still have the same issue on the latest revision

**Comment by jonathanpwang** [comment]
you may need to specify the `rust-toolchain` file, or update your own rust version?
