### ISSUE TITLE
can't build halo2-ecc as dependency

### ISSUE THREAD

**Issue by Ethan-000** [axiom-crypto/halo2-lib#61]
Hey

I can't seem to build halo2-ecc as a dependency.

Here is the screenshot

![halo2_ecc_import](https://github.com/axiom-crypto/halo2-lib/assets/70556667/011cb3d8-0179-432c-8149-186778476874)

**Comment by jonathanpwang** [comment]
This is a rust-toolchain issue: see https://github.com/axiom-crypto/halo2-lib/issues/22 

To fix, `echo "nightly-2022-10-28" > rust-toolchain`

**Comment by jonathanpwang** [comment]
Weird because I thought Cargo would use the rust-toolchain in the imported library
